---
title: "Enriched_genes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE, warning=FALSE, results="hide", echo=FALSE}
# setting up packages and conda environment
reticulate::use_condaenv("reticulate_PCHA", conda = "auto", required = TRUE) 
library(ggplot2)
library(scater)
library(scran)
library(SingleCellExperiment)
library(parallel)
library(Seurat)
library(ParetoTI)
```

```{r source_utils, echo=FALSE}
source("/Users/tudaga/Documents/github/BSSP_Pareto_cerebellum/ParetoTI_utils.R")
```

## Load data and objects
```{r load}
load('/Users/tudaga/Documents/github/BSSP_Pareto_cerebellum/Lug_Glob_Cand_analysis/hvgs_lug_glob_cand4.Rdata')
```


## Archetype 4
```{r archetpe_4, message=FALSE, warning=FALSE}
archetype = 'archetype_4'
sets_rows = labs[["enriched_sets"]]$x_name==archetype
print(labs[["enriched_sets"]][sets_rows, 2])

genes_rows = labs[["enriched_genes"]]$arch_name==archetype
enriched_genes_arc = labs[["enriched_genes"]]$genes[genes_rows]
print(enriched_genes_arc)

print(paste0("Plots for top 10 enriched genes in ", archetype))
gene_vec = head(enriched_genes_arc, 10)
l <- htmltools::tagList()
for (gene in gene_vec) {
  l[[gene]] <- make_3d_pc_plot_gene_arc(data_sce, arc_all, gene, 2.5, 3, archetype)
}
l
```

## Sex
```{r sex, message=FALSE, warning=FALSE}
p_pca = plot_arc(arc_data = arc_all, data = PCs4arch, 
                 which_dimensions = 1:3, line_size = 2.5,
                 data_lab = data_sce@colData$orig.ident,
                 text_size = 60, data_size = 2) 
plotly::layout(p_pca, title = paste0("Colored by sex"))
```
