---
title: "Markers"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE, warning=FALSE, results="hide", echo=FALSE}
# setting up packages and conda environment
reticulate::use_condaenv("reticulate_PCHA", conda = "auto", required = TRUE) 
library(ggplot2)
library(scater)
library(scran)
library(SingleCellExperiment)
library(parallel)
library(Seurat)
library(ParetoTI)
```

```{r source_utils, echo=FALSE}
source("/Users/tudaga/Documents/github/BSSP_Pareto_cerebellum/ParetoTI_utils.R")
```

## Load data and objects
```{r load}
load('/Users/tudaga/Documents/github/BSSP_Pareto_cerebellum/Lug_Glob_Cand_analysis/hvgs_lug_glob_cand4.Rdata')
```

## Plots
```{r plots, message=FALSE, warning=FALSE}
# Plot PCA colored by identity (celltype subtype)
scater::plotReducedDim(data_sce, ncomponents = 3, dimred = "PCA",
                       colour_by = "ident")

# Plot PCA colored by sex
scater::plotReducedDim(data_sce, ncomponents = 3, dimred = "PCA",
                       colour_by = "orig.ident")

# Plot PCA colored by spatial region
scater::plotReducedDim(data_sce, ncomponents = 3, dimred = "PCA",
                       colour_by = "region")

# Show variance explained by a polytope with each k (cumulative)
plot_arc_var(arc_ks, type = "varexpl", point_size = 2, line_size = 1.5) + theme_bw()

# Show variance explained by k-vertex model on top of k-1 model (each k separately)
plot_arc_var(arc_ks, type = "res_varexpl", point_size = 2, line_size = 1.5) + theme_bw()

# Show variance in position of vertices obtained using bootstraping 
# - use this to find largest k that has low variance
plot_arc_var(arc_ks, type = "total_var", point_size = 2, line_size = 1.5) +
  theme_bw() +
  ylab("Mean variance in position of vertices")

# Show t-ratio
plot_arc_var(arc_ks, type = "t_ratio", point_size = 2, line_size = 1.5) + theme_bw()
```



```{r markers_plots, message=FALSE, warning=FALSE}
gene_vec = c("Aldh1a3", "Slc6a5", "Htr2a", "Nxph1", "Cdh22")

print(gene_vec)
l <- htmltools::tagList()
for (gene in gene_vec) {
  l[[gene]] <- make_3d_pc_plot_gene(data_sce, arc_all, gene, 2.5, 3)
}
l
```




